{% set name = "libfatrop" %}
{% set version = "0.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/meco-group/fatrop/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 30354b4e7aeee8f475955518513f81d692cd0179d03c8553e78e3d3f9d443943
    patches:
      - do_not_hardcode_blasfeo_path.patch

build:
  skip: true  # [win]
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - libblasfeo

test:
  commands:
    - test -f $PREFIX/include/fatrop/fatrop.hpp  # [unix]
    - test -f $PREFIX/lib/libfatrop${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/cmake/fatropConfig.cmake   # [unix]
    - if not exist %PREFIX%\\Library\\cmake\\fatropConfig.cmake exit 1  # [win]
    - if not exist %LIBRARY_INC%\\fatrop\\fatrop.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\fatrop.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\fatrop.dll exit 1  # [win]

about:
  home: https://github.com/meco-group/fatrop
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Fatrop is a nonlinear optimal control problem solver that aims to be fast, support a broad class of optimal control problems and achieve a high numerical robustness.

extra:
  feedstock-name: fatrop
  recipe-maintainers:
    - traversaro
